name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -q

  playwright:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev-requirements.txt
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium
      - name: Start Streamlit app in background
        run: |
          python -m pip install --upgrade pip
          . .venv || true
          nohup bash -c "python -m streamlit run app.py &> streamlit.log &" || (python -m streamlit run app.py &)
      - name: Wait for app to start
        run: sleep 5
      - name: Run Playwright UI test (headless)
        env:
          PLAYWRIGHT_HEADLESS: '1'
        run: python scripts/playwright_test.py
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: scripts/screenshots/
